// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novotel.Infrastructure.Data;

#nullable disable

namespace Novotel.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231203011904_add")]
    partial class add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Novotel.Domain.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 3, 8, 19, 4, 195, DateTimeKind.Local).AddTicks(1145),
                            Description = "",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal House",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 3, 8, 19, 4, 195, DateTimeKind.Local).AddTicks(1225),
                            Description = "",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal House",
                            Occupancy = 3,
                            Price = 300.0,
                            Sqft = 540
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 3, 8, 19, 4, 195, DateTimeKind.Local).AddTicks(1233),
                            Description = "",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal House",
                            Occupancy = 4,
                            Price = 500.0,
                            Sqft = 650
                        });
                });

            modelBuilder.Entity("Novotel.Domain.Entities.HouseNumber", b =>
                {
                    b.Property<int>("House_Number")
                        .HasColumnType("int");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_Number");

                    b.HasIndex("HouseId");

                    b.ToTable("HousesNumbers");

                    b.HasData(
                        new
                        {
                            House_Number = 101,
                            HouseId = 1
                        },
                        new
                        {
                            House_Number = 102,
                            HouseId = 1
                        },
                        new
                        {
                            House_Number = 103,
                            HouseId = 1
                        },
                        new
                        {
                            House_Number = 201,
                            HouseId = 2
                        },
                        new
                        {
                            House_Number = 202,
                            HouseId = 2
                        });
                });

            modelBuilder.Entity("Novotel.Domain.Entities.HouseNumber", b =>
                {
                    b.HasOne("Novotel.Domain.Entities.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
