// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novotel.Infrastructure.Data;

#nullable disable

namespace Novotel.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Novotel.Domain.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 22, 20, 18, 34, 28, DateTimeKind.Local).AddTicks(6752),
                            Description = "",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal House",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 22, 20, 18, 34, 28, DateTimeKind.Local).AddTicks(6767),
                            Description = "",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal House",
                            Occupancy = 3,
                            Price = 300.0,
                            Sqft = 540
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 22, 20, 18, 34, 28, DateTimeKind.Local).AddTicks(6769),
                            Description = "",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal House",
                            Occupancy = 4,
                            Price = 500.0,
                            Sqft = 650
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
